In [1]:

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/catalog-subset/attr_subset.csv


In [2]:
import pandas as pd
import numpy as np
import warnings


import matplotlib.pyplot as plt
import io
import keras

warnings.filterwarnings("ignore")
pd.set_option('display.max_columns',100)
pd.set_option('display.max_colwidth',200)

!pip install tf_keras

!wget --quiet  https://raw.githubusercontent.com/tensorflow/models/master/official/nlp/tools/tokenization.py   
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import warnings

import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import ModelCheckpoint
import tensorflow_hub as hub 
import tokenization

from sklearn.metrics import accuracy_score, roc_curve, auc, classification_report, roc_auc_score, precision_recall_curve,confusion_matrix
from sklearn.model_selection import train_test_split

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


  Obtaining dependency information for tf_keras from https://files.pythonhosted.org/packages/19/26/ca8a6cca61f2a44f1e7ee71ebdb9c8dfbc4371f418db811cdca4641f6daa/tf_keras-2.15.0-py3-none-any.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 7.2 MB/s eta 0:00:00


In [3]:
data = pd.read_csv('/kaggle/input/catalog-subset/attr_subset.csv')
print(data.shape)
data.head()

(506287, 8)


asin  \
0  B01IBY1PI2   
1  B07TCTNF96   
2  B07Z86K31S   
3  B08SBGY2TC   
4  B08DP4R7WX   

                                                                                                                                    item_name  \
0  Vertx Mens Tactical Pants Cargo Utility with Pockets, Lightweight Casual Outdoor Work-Wear, Relaxed-Fit, Phantom LT 2.0, Smoke Grey, 31x30   
1                                                                                             Reebok Workout Ready Knit Pant, Black, XX-Large   
2   Doctor's Choice Compression Low Calf Crew Socks, Plantar Fasciitis, Achilles Tendonitis & Arch Support for Men & Women, 1 Pair, Tan/Large   
3            Softball Drawstring Bag for Girls, Eat Sleep Softball Repeat Backpack, Softball Player Gift, Teen Sport Pack Cinch Sack Tote Bag   
4             BioSteel Sports Drink, Great Tasting Hydration with 5 Essential Electrolytes, Blue Raspberry Flavor, 16.7 Fluid Ounces, 12-Pack   

  prep_type is_set certified_level  pack_ind  number_items_in_set  set_target  
0   bagging      Y             1.0         0                  1.0           0  
1   bagging      N             1.0         0                  NaN           0  
2   bagging      N             1.0         0                  NaN           0  
3   bagging      N             1.0         1                  NaN           0  
4   asinstk      N             1.0         1                 12.0           0

In [4]:
data['item_name'] = data['item_name'].fillna('unknown')
data.isnull().sum()

asin                        0
item_name                   0
prep_type                   0
is_set                      0
certified_level             1
pack_ind                    0
number_items_in_set    262700
set_target                  0
dtype: int64

In [5]:
def bert_encode(texts, tokenizer, max_len = 160):
    all_tokens = []
    all_masks = []
    all_segments = []
    
    for text in texts:
        text = tokenizer.tokenize(text)
        
        text = text[:max_len-2]
        input_sequence = ['[CLS]'] + text + ['[SEP]']
        pad_len = max_len - len(input_sequence)
        
        tokens = tokenizer.convert_tokens_to_ids(input_sequence)
        tokens += [0] * pad_len
        pad_masks = [1] * len(input_sequence) + [0] * pad_len
        segment_ids = [0] * max_len
        
        all_tokens.append(tokens)
        all_masks.append(pad_masks)
        all_segments.append(segment_ids)
        
    return np.array(all_tokens), np.array(all_masks), np.array(all_segments)

In [6]:
def build_model(bert_layer, max_len = 160):
    
    input_word_ids = Input(shape = (max_len,), dtype = tf.int32, name = 'input_word_ids')
    input_mask = Input(shape = (max_len, ), dtype = tf.int32, name = 'input_mask')
    segments_ids = Input(shape = (max_len,), dtype = tf.int32, name = 'segment_ids')
    
    _, sequence_output = bert_layer([input_word_ids, input_mask, segments_ids])
    clf_output = sequence_output[:, 0, :]
    out = Dense(1, activation = 'sigmoid')(clf_output)
    
    model = Model(inputs = [input_word_ids, input_mask, segments_ids], outputs = out)
    model.compile(Adam(lr = 2e-6), loss = 'binary_crossentropy', metrics = ['accuracy'])
    
    return model

# Load and pre-processing

In [7]:
%%time
module_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-24_H-1024_A-16/1"
bert_layer = hub.KerasLayer(module_url, trainable=True)

CPU times: user 21 s, sys: 4.83 s, total: 25.8 s
Wall time: 26.6 s


In [8]:
vocab_file = bert_layer.resolved_object.vocab_file.asset_path.numpy()
do_lower_case = bert_layer.resolved_object.do_lower_case.numpy()
tokenizer = tokenization.FullTokenizer(vocab_file, do_lower_case)

# Train/test split

In [9]:
data.set_target.value_counts()

set_target
0    487817
1     18470
Name: count, dtype: int64

# Downsample

In [10]:
set_dt = data[data["set_target"] == 1]
nonset_dt  = data[data["set_target"] == 0]
print(set_dt.shape)
print(nonset_dt.shape)

(18470, 8)
(487817, 8)


In [11]:
from sklearn.utils import resample
nonset_ds = resample(nonset_dt,
             replace=True,
             n_samples=len(set_dt),
             random_state=42)

print(nonset_ds.shape)

(18470, 8)


In [12]:
data_sub = pd.concat([set_dt, nonset_ds])
print(data_sub.shape)
data_sub.set_target.value_counts()

(36940, 8)


set_target
1    18470
0    18470
Name: count, dtype: int64

In [13]:
data_smp = data_sub.sample(2000, random_state = 42)
data_smp.set_target.value_counts()

set_target
0    1009
1     991
Name: count, dtype: int64

In [14]:
X = data_smp.item_name
y = data_smp.set_target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2023)

print('X_train shape:', X_train.shape)
print('X_test shape:', X_test.shape)
print('y_train shape:',y_train.shape)
print('y_test shape:',y_test.shape)

X_train shape: (1600,)
X_test shape: (400,)
y_train shape: (1600,)
y_test shape: (400,)


In [15]:
%%time

train_input = bert_encode(X_train.values, tokenizer, max_len = 160)
test_input = bert_encode(X_test.values, tokenizer, max_len = 160)
train_labels = y_train.values

CPU times: user 1.23 s, sys: 0 ns, total: 1.23 s
Wall time: 1.23 s


# Modeling

In [16]:
model = build_model(bert_layer, max_len = 160)
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_word_ids (InputLayer  [(None, 160)]                0         []                            
 )                                                                                                
                                                                                                  
 input_mask (InputLayer)     [(None, 160)]                0         []                            
                                                                                                  
 segment_ids (InputLayer)    [(None, 160)]                0         []                            
                                                                                                  
 keras_layer (KerasLayer)    [(None, 1024),               3351418   ['input_word_ids[0][0]',  

In [17]:
%%time

train_history = model.fit(train_input, train_labels, validation_split = 0.2, epochs = 10, batch_size = 16)
model.save('model.h5')

Epoch 1/10
80/80 [==============================] - 218s 2s/step - loss: 0.9733 - accuracy: 0.4688 - val_loss: 0.7591 - val_accuracy: 0.5063
Epoch 2/10
80/80 [==============================] - 129s 2s/step - loss: 0.7345 - accuracy: 0.4930 - val_loss: 0.6941 - val_accuracy: 0.5063
Epoch 3/10
80/80 [==============================] - 129s 2s/step - loss: 0.7079 - accuracy: 0.4930 - val_loss: 0.7132 - val_accuracy: 0.4938
Epoch 4/10
80/80 [==============================] - 129s 2s/step - loss: 0.6980 - accuracy: 0.5289 - val_loss: 0.6950 - val_accuracy: 0.4938
Epoch 5/10
80/80 [==============================] - 129s 2s/step - loss: 0.7135 - accuracy: 0.4883 - val_loss: 0.7480 - val_accuracy: 0.5063
Epoch 6/10
80/80 [==============================] - 129s 2s/step - loss: 0.7222 - accuracy: 0.4961 - val_loss: 0.7000 - val_accuracy: 0.5063
Epoch 7/10
80/80 [==============================] - 129s 2s/step - loss: 0.7191 - accuracy: 0.5008 - val_loss: 0.7127 - val_accuracy: 0.5063
Epoch 8/10
80

In [18]:
%%time
train_pred = model.predict(train_input)

50/50 [==============================] - 57s 1s/step
CPU times: user 50.1 s, sys: 7.25 s, total: 57.3 s
Wall time: 57.7 s


In [19]:
auc_train = roc_auc_score(y_train, train_pred)
print('train roc:', auc_train )

train roc: 0.5020414349576791


In [20]:
print('accuracy score: \n', accuracy_score(y_train, np.round(train_pred)), '\n')

print('classification report \n', classification_report(y_train, np.round(train_pred)), '\n')

print('confusion matrix \n', confusion_matrix(y_train, np.round(train_pred)), '\n')

accuracy score: 
 0.498125 

classification report 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       803
           1       0.50      1.00      0.66       797

    accuracy                           0.50      1600
   macro avg       0.25      0.50      0.33      1600
weighted avg       0.25      0.50      0.33      1600
 

confusion matrix 
 [[  0 803]
 [  0 797]] 



In [21]:
%%time
test_pred = model.predict(test_input)

13/13 [==============================] - 16s 1s/step
CPU times: user 14 s, sys: 1.77 s, total: 15.8 s
Wall time: 16.1 s


In [22]:
test_pred

array([[0.52702355],
       [0.52702355],
       [0.52702355],
       [0.5270237 ],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.5270237 ],
       [0.52702355],
       [0.5270237 ],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.52702355],
       [0.527

In [23]:
auc = roc_auc_score(y_test, test_pred)
print('test roc:', auc)

test roc: 0.5057676909218296


In [24]:
print('accuracy score: \n', accuracy_score(y_test, np.round(test_pred)), '\n')

print('classification report \n', classification_report(y_test, np.round(test_pred)), '\n')

print('confusion matrix \n', confusion_matrix(y_test, np.round(test_pred)), '\n')

accuracy score: 
 0.485 

classification report 
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       206
           1       0.48      1.00      0.65       194

    accuracy                           0.48       400
   macro avg       0.24      0.50      0.33       400
weighted avg       0.24      0.48      0.32       400
 

confusion matrix 
 [[  0 206]
 [  0 194]] 

